### PR TITLE
add rambam chapter counts

### PR DESCRIPTION
**Pull request by hudcap**
Thanks for creating this repo!
Please let me know if you want me to change the format (or anything else).

### CODE REVIEW

**Comment by bandleader** [comment]
Merged, thanks! (converted to JSON)

I actually think we should do the different spellings etc. as I had in the Shas file, which means moving to a tabular format like TSV. (I assume you don't have data for that).

I'm wondering if a better idea is to have a generic map of Hebrew words along with their canonical Sefardi and Ashkenazi English transliterations. Then we can simply run that on any input. What do you think? (In general I foresee issues with things like Mitzvas/Mitzvos/Matzos, Shevuos/Shavuos, though I'm not sure it will be an issue specifically in titles of the basic Torah texts.)

**Comment by hudcap** [comment]
Especially since the goal is for people to contribute what they already have, I think the map is a great idea, so any incoming data can be handled easily. I remember someone asking about this (or something similar) on frumdevs, but I can't find it.

**Comment by hudcap** [comment]
Side note: I was thinking of converting to json, but I thought comments weren't supported in json, and there was one comment in there—am I mistaken about comments?

**Comment by bandleader** [comment]
The official JSON spec doesn't allow comments and many/most parsers will indeed fail on them. However I left the comment in as it sounds important, and consumers can easily remove it

**Pull request merged**
